services:
  database:
    build:
      context: ./database/sqlserver
    container_name: sqlserver-database
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      SA_PASSWORD: "sq!server@admin"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
  api:
    build:
      context: ./backend
    container_name: aspnet-api
    depends_on:
      - database
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=MyDb;User Id=SA;Password=sq!server@admin;TrustServerCertificate=True;"
      ASPNETCORE_URLS: "http://+:80"
    # stdin_open: true
    # tty: true
  web:
    build:
      context: ./frontend
    container_name: react-frontend
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

volumes:
  mssql-data:
