services:
  database:
    build:
      context: ./database/sqlserver
    container_name: sqlserver-database
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      SA_PASSWORD: "sq1server@Admin"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
  api:
    build:
      context: ./backend
    container_name: aspnet-api
    depends_on:
      - database
    ports:
      - "5029:80"
    volumes:
      - ./backend:/app
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=TestDB;User Id=SA;Password=sq1server@Admin;TrustServerCertificate=True;"
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_ENVIRONMENT: Development
    # stdin_open: true
    # tty: true
  web:
    build:
      context: ./frontend
    container_name: react-frontend
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

volumes:
  mssql-data:
